// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AnalyzeDiskGrowth(arg1:model.DiskGrowthOptions):Promise<model.DiskGrowthResult>;

export function CancelTask(arg1:string):Promise<void>;

export function Clean(arg1:model.CleanRequest):Promise<model.CleanResult>;

export function CleanGrowthPaths(arg1:model.GrowthCleanRequest):Promise<model.CleanResult>;

export function CompareSnapshotPath(arg1:string,arg2:string,arg3:string):Promise<model.SnapshotPathCompareResult>;

export function CompareSnapshots(arg1:string,arg2:string):Promise<model.SnapshotCompareResult>;

export function DeleteSnapshot(arg1:string):Promise<void>;

export function ListSnapshots():Promise<Array<model.SnapshotInfo>>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function Scan(arg1:model.ScanOptions):Promise<model.ScanResult>;

export function TakeSnapshot(arg1:string,arg2:string):Promise<model.DiskSnapshot>;
