// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDiskGrowth(arg1) {
  return window['go']['main']['App']['AnalyzeDiskGrowth'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function Clean(arg1) {
  return window['go']['main']['App']['Clean'](arg1);
}

export function CleanGrowthPaths(arg1) {
  return window['go']['main']['App']['CleanGrowthPaths'](arg1);
}

export function CompareSnapshotPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompareSnapshotPath'](arg1, arg2, arg3);
}

export function CompareSnapshots(arg1, arg2) {
  return window['go']['main']['App']['CompareSnapshots'](arg1, arg2);
}

export function DeleteSnapshot(arg1) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1);
}

export function ListSnapshots() {
  return window['go']['main']['App']['ListSnapshots']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function TakeSnapshot(arg1, arg2) {
  return window['go']['main']['App']['TakeSnapshot'](arg1, arg2);
}
