// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function Clean(arg1) {
  return window['go']['main']['App']['Clean'](arg1);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}
