// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CancelTask(arg1:string):Promise<void>;

export function Clean(arg1:model.CleanRequest):Promise<model.CleanResult>;

export function Scan(arg1:model.ScanOptions):Promise<model.ScanResult>;
